fun main() {
    val day1Calculator = Day1Calculator()
    val day2Calculator = Day2Calculator()
    val day3Calculator = Day3Calculator()
    val day4Calculator = Day4Calculator()
    val day5Calculator = Day5Calculator()
    val day6Calculator = Day6Calculator()
    val day1_1 = day1Calculator.calculatePart1()
    val day1_2 = day1Calculator.calculatePart2()
    val day2_1 = day2Calculator.calculatePart1()
    val day2_2 = day2Calculator.calculatePart2()
    val day3_1 = day3Calculator.calculatePart1()
    val day3_2 = day3Calculator.calculatePart2()
    val day4_1 = day4Calculator.calculatePart1()
    val day4_2 = day4Calculator.calculatePart2()
    val day5_1 = day5Calculator.calculatePart1()
    val day5_2 = day5Calculator.calculatePart2()
    val day6_1 = day6Calculator.calculatePart1()
    val day6_2 = day6Calculator.calculatePart2()
    println("Day 1 - part 1: $day1_1")
    println("Day 1 - part 2: $day1_2")
    println()
    println("Day 2 - part 1: $day2_1")
    println("Day 2 - part 2: $day2_2")
    println()
    println("Day 3 - part 1: $day3_1")
    println("Day 3 - part 2: $day3_2")
    println()
    println("Day 4 - part 1: $day4_1")
    println("Day 4 - part 2: $day4_2")
    println()
    println("Day 5 - part 1: $day5_1")
    println("Day 5 - part 2: $day5_2")
    println()
    println("Day 6 - part 1: $day6_1")
    println("Day 6 - part 2: $day6_2")
}
